### ISSUE TITLE
Variables beginning with Underscore?

### ISSUE THREAD

**Issue by SatheeshJM** [scijava/parsington#20]
If I evaluate a condition for a variable beginning with underscore(`_` ), I get the error 
```
java.lang.IllegalArgumentException: Invalid character at index 0
```

Is there any way to override this behaviour?

**Comment by ctrueden** [comment]
@SatheeshJM Yes. You can override the `ParseOperation` method `isIdentifierStart` to accept underscores as well. I pushed an example: 12b68ba25254edb8b8b689b7c6171b2c34499b18.

I am tempted to change the default implementation of this method to accept underscores as well, since it's closer to the behavior of popular languages like Java and Python. But it could potentially break behavior for other customized parsers out there. In this case though, that risk seems low to me. What do you think? Should we change it? Or leave it alone?

**Comment by SatheeshJM** [comment]
I dont really mind what the default behaviour is, as long as there is a way to override it! 
Cheers!
